export const LOGIN = 'LOGIN';
export const SAVE_DATA_USER = 'SAVE_DATA_USER';
export const SIGNUP_EMAIL = 'SIGNUP_EMAIL';
export const SET_DATA_SIGNUP = 'SET_DATA_SIGNUP';
export const SIGNUP_GOOGLE = 'SIGNUP_GOOGLE';
export const SIGNUP_FACEBOOK = 'SIGNUP_FACBOOK';
export const SIGNIN_GOOGLE = 'SIGNIN_GOOGLE';
export const SIGNIN_FACEBOOK = 'SIGNIN_FACBOOK';
export const SET_USER_ID = 'SET_USER_ID';
export const LOGOUT = 'LOGOUT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const SAVE_TOKEN_REDUX = 'SAVE_TOKEN_REDUX';

export const UPDATE_SIGNUP_INFO = 'UPDATE_SIGNUP_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const RESET_NEW_PASSWORD = 'RESET_NEW_PASSWORD';
export const RESET_DATA_SIGNUP = 'RESET_DATA_SIGNUP';

//PROFILE
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_NOTIFICATION = 'CHANGE_NOTIFICATION'
export const GET_PROFILE_USER = 'GET_PROFILE_USER';
export const SET_PROFILE_USER = 'SET_PROFILE_USER'
export const CHANGE_PROFILE_USER = 'CHANGE_PROFILE_USER'

