// UNAUTHENTICATION
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const WELCOME = 'WELCOME';
export const SIGNIN = 'SIGNIN';
export const CHOOSE_ROLE = 'CHOOSE_ROLE';
export const UPDATE_NEW_PASSWORD = 'UPDATE_NEW_PASSWORD';

// AUTHENTICATION
export const TABBAR = 'TABBAR';
export const PROFILE = 'PROFILE';
export const BASIC_INFORMATION = 'HOME_PROFILE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const PROFILE_LIFE_STYLE = 'PROFILE_LIFE_STYLE';

